- src/nextapp/pages/redirect/[id].tsx
Fixes #144 
End of life redirect page has a clear CTA link style.
> Style docs link on redirect page.

- src/lists/extensions/Namespace.ts
- src/services/keystone/index.ts
- src/services/keystone/user.ts
Fixes #188 
There is a gap in the user data in keycloak and portal database. We usually fetch namespace user list to send notifications after generation of credentials. Due to non availability of user details in the database, the fetch user function failed and due to which it generated an error during credential generation.
> Fix to allow credential generation even after other namespace users are not found in the database but are available in Keycloak

- src/nextapp/components/controls/rate-limiting.tsx
- src/nextapp/pages/manager/consumers/[id].tsx
- src/test/mock-server/server.js
Fixes #167 
Uses `extForeignKey` to set the selected dropdown value in the plugin edit dialog.
> Use extForeignKey for value in controls dialog

- src/nextapp/components/access-request-form/access-request-dialog.tsx
- src/nextapp/components/auth-action/auth-action.tsx
Quick fix that switches the API Directory `Request Access` button to always be in an enabled state, but redirect to login if the user isn't signed in. Also contains a style change for the `Login` button to follow BC Design Guidelines.
> Quick fix for request access button and login styles

- src/nextapp/components/ns-breadcrumb/ns-breadcrumb.tsx
- src/nextapp/components/page-header/page-header.tsx
Consistently formats breadcrumbs as `Namespaces (Namespace Name) > ...`
> Adjust breadcrumbs for consistency.

- src/auth/auth-oauth2-proxy.js
- src/authz/graphql-whitelist/httplocalhost4180managerconsumers-0c6fa7.gql
- src/authz/graphql-whitelist/httplocalhost4180managerconsumers-d3af35.gql
- src/authz/graphql-whitelist/httplocalhost4180managerconsumers-ffe211.gql
- src/nextapp/components/access-request/access-request-dialog.tsx
- src/nextapp/components/access-request/access-requests-list.tsx
- src/nextapp/components/access-request/edit-dialog.tsx
- src/nextapp/components/access-request/grant-access-dialog.tsx
- src/nextapp/pages/manager/consumers/index.tsx
- src/services/workflow/consumer-filters.ts
Fixes:
- access requests appearing when credentials not collected
- user identity provider properties not updating on login
- toast for grant access not showing error
- consumer filter not filtering for acl-only flow
> Release 1.2 Hotfix Consumer Filters for acl-only flows

- src/authz/graphql-whitelist/httplocalhost4180devportalapplications-7fc130.gql
- src/authz/graphql-whitelist/httplocalhost4180devportalrequestsnew610c1e2329ee4c2072b16fa8-312522.gql
- src/mocks/handlers.js
- src/mocks/resolvers/applications.js
- src/nextapp/components/access-request-form/access-request-dialog.tsx
- src/nextapp/components/access-request-form/application-select.tsx
- src/nextapp/components/access-request/edit-dialog.tsx
- src/nextapp/components/new-application/new-application-dialog.tsx
- src/nextapp/pages/devportal/applications/index.tsx
> Feature/sprint 56 UI fixes

- src/nextapp/components/service-account-create/service-account-create.tsx
- src/nextapp/pages/manager/service-accounts/index.tsx
Implements the new Service Accounts UI, fixes #597
> Service Accounts UI Refresh

- src/authz/graphql-whitelist/httplocalhost3000admingraphiql-19e539.gql
- src/authz/graphql-whitelist/httplocalhost3000admingraphiql-8b0644.gql
- src/mocks/handlers.js
- src/mocks/resolvers/applications.js
- src/nextapp/components/application-services/application-services.tsx
- src/nextapp/components/edit-application/edit-application.tsx
- src/nextapp/components/edit-application/index.ts
- src/nextapp/pages/devportal/applications/index.tsx
Fixes #675
**Preview URL:** https://api-services-portal-feature-application-edit.apps.silver.devops.gov.bc.ca/devportal/applications
> Add application edit dialog

- e2e/cypress.config.ts
- e2e/cypress/fixtures/api.json
- e2e/cypress/fixtures/apiowner.json
- e2e/cypress/fixtures/cors/kong-cors-plugin-config.json
- e2e/cypress/fixtures/developer.json
- e2e/cypress/pageObjects/apiDirectory.ts
- e2e/cypress/pageObjects/keycloakGroup.ts
- e2e/cypress/pageObjects/keycloakUsers.ts
- e2e/cypress/pageObjects/namespaceAccess.ts
- e2e/cypress/pageObjects/webApp.ts
- e2e/cypress/support/auth-commands.ts
- e2e/cypress/support/commands.ts
- e2e/cypress/support/global.d.ts
- e2e/cypress/support/util-commands.ts
- e2e/cypress/tests/02-client-credential-flow/10-jwks-publicKey-access-rqst.cy.ts
- e2e/cypress/tests/02-client-credential-flow/11-jwt-publlicKey-access-approve-api-rqst.cy.ts
- e2e/cypress/tests/03-manage-labels/03-filter-labels.cy.ts
- e2e/cypress/tests/03-manage-labels/05-link-consumers.ts
- e2e/cypress/tests/06-refresh-credential/01-api-key.cy.ts
- e2e/cypress/tests/15-org-assignment/02-multiple-org-admin.ts
- e2e/cypress/tests/15-org-assignment/03-multiple-org-admin-org-unit.ts
- e2e/cypress/tests/16-aps-api/05-authorizationProfiles.cy.ts
- e2e/cypress/tests/17-CORS/01-create-api.cy.ts
- e2e/package-lock.json
- e2e/package.json
- local/html-sample-app/Dockerfile
- local/html-sample-app/package.json
- local/html-sample-app/public/index.html
- local/html-sample-app/public/script.js
- local/html-sample-app/server.js
* Added following scenarios: 1)Cypress test to verify free (Public) access
2)Cypress Test - Delete Service account
3)Cypress Test - Verify rate_limiting_902 and rate_limiting plugins by applying them to different level 4)Cypress Test for Org Admin
* Added scenario for free elevated access rate limiting and update test execution sequence
* Update authorization profile -inheritFrom scenario and update the execution order
* Add first pass at public keys addition to access key management
* Update free-elivated scenarios, added Link consumer to namespace scenarios and added test-dataid
* Update free-elevated scenario
* upd backend for request access dialog signed jwt
* upd backend for my access update signed jwt data
* fix copy button
* add backend graphql call for updating cert details
* …
> Cypress org admin (#823)

- .github/workflows/ci-build-feeders.yaml
- feeds/README.md
- feeds/ckan/index.js
- feeds/index.js
- feeds/utils/transfers.js
Feature branch: https://api-services-portal-feature-bcdc-sync-fix.apps.silver.devops.gov.bc.ca/signout
> Fix BCDC Datasets out of sync

- .github/workflows/ci-feat-url.yml
- src/nextapp/pages/devportal/index.tsx
- src/nextapp/pages/manager/index.tsx
Two changes: 
- adding the Box component to make dev and manager index pages match the main page
- GHA to add the feature branch deployment URL to PRs
---
🚀 Feature branch deployment: https://api-services-portal-feature-index-pages.apps.silver.devops.gov.bc.ca
> match style of main index page

- src/mocks/resolvers/api-directory.js
- src/nextapp/pages/devportal/api-directory/[id].tsx
- src/nextapp/shared/styles/markdown.module.css
- src/package.json
New rendering of markdown on the API Directory detail page:
---
🚀 Feature branch deployment: https://api-services-portal-feature-dataset-markdown.apps.silver.devops.gov.bc.ca
> Dataset formatting fix

- e2e/README.md
- e2e/test-data-dependencies.md
> add test dependencies

- e2e/cypress/tests/19-api-v3/03-gateways.ts
- src/controllers/v3/GatewayController.ts
- src/controllers/v3/openapi.yaml
> return display name on /gateways

- src/nextapp/components/namespace-access/organization-groups-access.tsx
Small fix to change `Namespace.View` to `Gateway.View` on 'Organization groups with access' tab, using the same approach as the other components in `src/nextapp/components/namespace-access`.
> replace Namespace with Gateway in org permission

- src/controllers/v3/OrganizationController.ts
- src/controllers/v3/openapi.yaml
- fixes #1135 
---
🚀 Feature branch deployment: https://api-services-portal-feature-org-error.apps.silver.devops.gov.bc.ca
> match GatewayController activity in OrgController v3

- src/nextapp/pages/manager/gateways/list.tsx
- fixes #1167 
I believe this is the first instance in which we have a clickable item / card sort of situation. This is a little one-off addition using Chakra inline styles but if we wanted to implement this sort of thing more widely, we could come up with a reusable component.
Or we could continue to use inline styles and handle each component individually.
---
🚀 Feature branch deployment: https://api-services-portal-feature-click-gateway-item.apps.silver.devops.gov.bc.ca
> clickable items in Gateways list

- src/nextapp/pages/manager/gateways/detail.tsx
- src/nextapp/pages/manager/gateways/list.tsx
Follows up on Tim's comment on #1179 - https://github.com/bcgov/api-services-portal/pull/1179#pullrequestreview-2307883242
> I'm wondering if we're able to style the Gateway display name with an underline based on the state of the parent to better match the styling of cards in the Gateways manager:
We think the hover background is rather dark but apparently that's the recommendation in the BC design tokens.
---
🚀 Feature branch deployment: https://api-services-portal-feature-click-gateway-item.apps.silver.devops.gov.bc.ca
---
🚀 Feature branch deployment: https://api-services-portal-feature-click-gateway-item.apps.silver.devops.gov.bc.ca
> tweak style for gateway list item hover

- .github/workflows/aps-cypress-e2e.yaml
- .github/workflows/scripts/feeder-init/legal.yaml
- e2e/cypress/tests/20-gateways/02-dropdown.ts
> fix tests to handle redirect away from your products

- src/nextapp/pages/devportal/api-directory/your-products.tsx
- src/nextapp/pages/manager/gateways/detail.tsx
- src/nextapp/shared/services/auth/auth-context.tsx
- src/nextapp/shared/services/auth/use-session.ts
- Fixes #1122 
---
🚀 Feature branch deployment: https://api-services-portal-feature-click-on-gateway.apps.silver.devops.gov.bc.ca
---
🚀 Feature branch deployment: https://api-services-portal-feature-click-on-gateway.apps.silver.devops.gov.bc.ca
> fix for click on gateway error
