src/nextapp/components/products-list/dataset-input.tsx
src/nextapp/components/products-list/edit-product.tsx
src/nextapp/components/products-list/organization-select.tsx
src/nextapp/shared/queries/organization-queries.ts
src/nextapp/shared/types/query.types.ts
src/services/keystone/types.ts
src/test/mock-server/data/db.js
src/test/mock-server/data/example-data.js
src/test/mock-server/server.js

Fixes issue where previously set datasets were not being backfilled into the product edit form.
Fixes #41

Fix backfilling of datasets in edit dialog

---

src/authz/whitelist.json
src/nextapp/components/docs/doc-header.tsx
src/nextapp/components/docs/index.ts
src/nextapp/components/docs/internal-link.tsx
src/nextapp/pages/docs/[slug].tsx
src/nextapp/pages/docs/index.tsx
src/nextapp/shared/services/api.ts
src/test/mock-server/server.js

Fixes #56 
There were inconsistent URLs for the server-side rendering and some clean-up of types. Added new `useRestApi` hook.

Documentation section clean up

---

.github/ISSUE_TEMPLATE/issue.md

adding an issue template which can be used to create more descriptive task/bug/story

---

src/batch/data-rules.ts
src/batch/feed-worker.ts
src/batch/hooks/handleNameChange.ts
src/batch/hooks/index.ts

Batch name change handling

---

src/nextapp/components/discovery-list/discovery-list-item.tsx
src/nextapp/pages/devportal/access/index.tsx
src/nextapp/pages/devportal/api-directory/[id].tsx
src/nextapp/pages/devportal/api-directory/index.tsx
src/nextapp/pages/index.tsx
src/nextapp/shared/data/links.ts

Fixes #82 
Fixes #95
Fixes #81

upd directory title and markdown

---

src/authz/whitelist.json
src/nextapp/components/access-list/access-list-item.tsx
src/nextapp/components/access-list/collect-credential-list.tsx
src/nextapp/components/access-list/index.ts
src/nextapp/components/access-requests/access-requests.tsx
src/nextapp/components/consumer-authz/consumer-authz.tsx
src/nextapp/pages/devportal/access/index.tsx
src/nextapp/pages/devportal/api-directory/[id].tsx
src/nextapp/pages/devportal/poc/access/index.tsx
src/nextapp/pages/devportal/requests/new/[id].tsx
src/nextapp/pages/devportal/requests/new/tokens.tsx
src/services/workflow/apply.ts

Fixes #78 
Enhancements:
* Disables the "Request Access" button when there are no protected environments for the API
* On "My Access", when you mouse over the Pending/Approved Icon, show the Application that the access relates to
* Display requests that have credentials which have not been collected (and have option to cancel request)
* Don't show public flows in the authorization panel on Consumer detail page

Improved handling of Public API and credential collection

---

src/nextapp/components/new-application/new-application-dialog.tsx

Fixes #116 
Form validation messages are displayed when attempting to create an invalid application

Add new pattern to trigger form errors in application create dialog

---

src/nextapp/components/namespace-menu/namespace-menu.tsx
src/test/mock-server/data/db.js

Fixes #123 
Namespace menu list is sorted alphabetically

Add alphabetical sorting to namespace menu

---

src/authz/whitelist.json

Noticed the change in route from discovery to directory - updated authz template to reflect this change

api-discovery

---

.github/workflows/ci-build-deploy.yaml
src/nextapp/pages/manager/services/[id].tsx
src/nextapp/pages/manager/services/index.tsx
src/nextapp/shared/config.ts

Fixes #125 
Moves the view metrics button from the view page to the services index page.

Move metrics button to the services index page.

---

.github/workflows/ci-build-deploy.yaml
.github/workflows/nohup.out
.github/workflows/scripts/feeder-init/legal.yaml
.github/workflows/scripts/feeder-init/platform-authz-profile.yaml
.github/workflows/scripts/feeder-init/platform-gwa-api.yaml
.github/workflows/scripts/init.sh
.github/workflows/scripts/template.py
src/lists/CredentialIssuer.js
src/nextapp/components/authorization-profile-controls/authentication.tsx
src/nextapp/pages/devportal/requests/new/[id].tsx
src/services/keycloak/client-registration-service.ts
src/services/keycloak/templates/client-template-client-jwt.ts
src/services/keycloak/user-service.ts
src/services/workflow/apply.ts
src/services/workflow/client-credentials.ts
src/services/workflow/generate-credential.ts
src/services/workflow/types.ts

Fixes #137 
Fixes #108 
Closes #101 
Closes #150 
There are also CI/CD Pipeline changes to seed feature branch deployments with the Gateway API Product Environment configuration so that features such as Namespace Management will work.  Fixes #165

Signed JWT and Client Credential Changes

---

src/authz/whitelist.json
src/nextapp/components/new-application/new-application-dialog.tsx
src/nextapp/components/new-application/new-application.tsx
src/nextapp/pages/devportal/applications/index.tsx
src/nextapp/pages/devportal/requests/new/[id].tsx

Create Application From Access Request Page

---

feeds/kong/index.js
feeds/utils/portal.js
src/batch/feed-worker.ts
src/lists/GatewayRoute.js
src/lists/GatewayService.js
src/server.ts
src/services/keystone/batch-service.ts
src/services/workflow/delete-gateway-config.ts
src/services/workflow/index.ts

Add delete cleanup logic for Kong data on Portal

---

src/nextapp/components/services-list/metric-graph.tsx

Fixes issue where an empty metrics data set for a service threw an error.

Fix graph error.

---

src/batch/transformations/connectExclusiveOne.ts
src/lists/Activity.js

fix the activity error

---

src/authz/graphql-whitelist/httplocalhost4180managerproducts-a7ee78.gql
src/authz/graphql-whitelist/httplocalhost4180managerproducts-b3627d.gql
src/authz/graphql-whitelist/httplocalhost4180managerproducts-fbb712.gql
src/authz/matrix.csv
src/controllers/DirectoryController.ts
src/nextapp/components/api-product-item/api-product-item.tsx
src/nextapp/components/namespace-manager/export-report.tsx
src/nextapp/components/namespace-manager/index.ts
src/nextapp/components/namespace-manager/namespace-manager.tsx
src/nextapp/components/products-list/dataset-input.tsx
src/nextapp/components/products-list/edit-product.tsx
src/nextapp/components/products-list/queries.ts
src/nextapp/shared/queries/dataset-queries.ts
src/nextapp/shared/queries/products-queries.ts
src/server.ts
src/services/report/workbook.service.ts
src/services/workflow/index.ts
src/services/workflow/validate-active-environment.ts
src/test/services/workflow/setup.js
src/test/services/workflow/validate-active-environment.test.js

Anonymous access fix and report generation fix

---

e2e/cypress/pageObjects/logout.ts
e2e/cypress/pageObjects/products.ts
e2e/cypress/support/auth-commands.ts
local/feeder-init/dataset-gwa.yaml
local/feeder-init/init.sh
local/feeder-init/product-initializer.yaml

1)Remove steps to select the value from Organization and Organization Unit for Edit Product page
2)Update action to select Term and condition and Kong Config from the drop down in Edit Environment
3)Update step to verify user name in Sign Out button

Update 01-create-api.spec.ts for following changes:

---

docker-compose.yml
e2e/cypress/fixtures/apiowner.json
e2e/cypress/fixtures/developer.json
e2e/cypress/fixtures/state/store.json
e2e/cypress/tests/01-create-api.spec.ts
e2e/cypress/tests/02-team-access.spec.ts
e2e/cypress/tests/03-rqst-access.spec.ts
e2e/cypress/tests/manage-control/09-ip-restriction.ts
e2e/cypress/tests/manage-control/10-rate-limiting.ts
local/feeder-init/developer-user.yaml
local/feeder-init/idir-user.yaml
local/feeder-init/platform-authz-profile.yaml
local/keycloak/master-realm.json

1)Create Janis,Harley user in Keycloak
2)Update users in feeder initializer
3)Update the user to the Persona name (Janis, Harley, Mark, Wendy)
4)Update the existing automation scenarios to the persona name to make automation scenarios consistent with the persona used in the standard documentations.

Update Cypress scenarios with Personas

---

src/nextapp/components/card/card.stories.mdx
src/nextapp/components/card/card.tsx
src/nextapp/shared/theme.ts
src/stories/Select.stories.tsx
src/stories/Table.stories.mdx
src/stories/Textarea.stories.tsx

This is a catch all PR for existing components that needs some layout or functionality revisions.
Currently fixes are for:

Fix select and focus states

---

.github/workflows/aps-cypress-e2e.yaml

Fixes https://dpdd.atlassian.net/browse/APS-932

Additional step added to cypress e2e test gh action to create github issue with failed tests

---

src/nextapp/components/authorization-profile-form/authorization-form.tsx

Parses clientMappers default value, which is a stringified JSON object when editing.

Fix client mappers

---

.github/workflows/ci-build-deploy.yaml
.github/workflows/scripts/feeder-init/dataset-test.yaml
.github/workflows/scripts/feeder-init/organization-unit.yaml
.github/workflows/scripts/init.sh
src/authz/graphql-whitelist/httplocalhost4180devportalaccess-c3bf09.gql
src/authz/graphql-whitelist/httplocalhost4180devportalaccess-fabe95.gql
src/authz/matrix.csv
src/codegen.yaml
src/lists/extensions/CredentialRegenerate.ts
src/nextapp/components/access-list/access-list-item.tsx
src/nextapp/components/access-list/access-list-row.tsx
src/nextapp/components/access-request-form/access-request-credentials.tsx
src/nextapp/components/access-request-form/generate-credentials-dialog.tsx
src/nextapp/components/access-request-form/regenerate-credentials-dialog.tsx
src/nextapp/components/generate-credential/generate-credential.tsx
src/nextapp/pages/devportal/access/index.tsx
src/nextapp/shared/theme.ts
src/nextapp/shared/types/query.types.ts
src/server.ts
src/services/keycloak/client-service.ts
src/services/keystone/service-access.ts
src/services/keystone/types.ts
src/services/kong/consumer-service.ts
src/services/workflow/generate-credential.ts
src/services/workflow/kong-api-key-replace.ts
src/test/integrated/keycloak/client.ts
src/test/integrated/keystonejs/serviceAccess.ts
src/test/mock-server/schemas.js
src/test/mock-server/server.js

Regenerate Credentials

---

src/nextapp/components/authorization-profile-form/authentication-form.tsx
src/nextapp/components/authorization-profile-form/authorization-profile-dialog.tsx
src/test/mock-server/server.js

Remove Kong API Key

---

src/nextapp/components/auth-action/auth-action.tsx

Removes the BCSC menu item from the app bar profile menu.

Remove bcsc user menu option

---

e2e/cypress/tests/08-aps-api/06-api-directory.ts

Update expected status code when call the API with non exist director ID

Update expected status code when call the API with non exist directory ID

---

src/authz/graphql-whitelist/httplocalhost3000admingraphiql-16c14e.gql
src/authz/graphql-whitelist/httplocalhost4180devportalapidirectory609c5bf79b8ceca36d31ce95-4f8965.gql
src/authz/graphql-whitelist/httplocalhost4180devportalapidirectorypreviewtrue-e22f2c.gql
src/authz/graphql-whitelist/httplocalhost4180managerauthorizationprofiles-03e7f2.gql
src/authz/graphql-whitelist/httplocalhost4180managerauthorizationprofiles-f8e05c.gql
src/authz/graphql-whitelist/httplocalhost4180managerconsumers-17d5dc.gql
src/authz/graphql-whitelist/httplocalhost4180managerconsumers-e5e2fa.gql
src/authz/graphql-whitelist/httplocalhost4180managernamespaces-16efcb.gql
src/authz/graphql-whitelist/httplocalhost4180managernamespaces-7aa8f8.gql
src/authz/graphql-whitelist/httplocalhost4180managernamespaces-c88e76.gql
src/mocks/resolvers/consumers.js
src/nextapp/components/access-request-form/access-request-form.tsx
src/nextapp/components/access-request/access-request-dialog.tsx
src/nextapp/components/access-request/access-requests-list.tsx
src/nextapp/components/business-profile/business-profile-content.tsx
src/nextapp/components/manage-labels/manage-labels.tsx
src/nextapp/components/profile-card/profile-card.tsx
src/nextapp/components/user-profile/user-profile.stories.mdx
src/nextapp/components/user-profile/user-profile.tsx
src/nextapp/pages/manager/authorization-profiles/[id].tsx
src/nextapp/pages/manager/consumers/[id].tsx
src/nextapp/pages/manager/consumers/index.tsx
src/nextapp/shared/hooks/use-namespace-breadcrumbs.ts
src/nextapp/shared/theme.ts

Consumer related UI bugs fixes.
Fixes #499, #500, #501, #502, #503, #513

Revisions for UX

---

src/nextapp/components/access-request-form/access-request-dialog.tsx
src/nextapp/components/api-product-item/api-product-item.tsx
src/test/mock-server/server.js

Access request button tweaks.

---

src/nextapp/components/namespace-menu/namespace-menu.tsx

Co-authored-by: Justin Tendeck <justin.tendeck@goc.bc.ca>

fix create ns issue (#531)

---

e2e/cypress/pageObjects/consumers.ts
e2e/cypress/pageObjects/products.ts

Added wait to make test not flaky in remote execution

Added wait to make test not flaky in remote execution

---

src/authz/graphql-whitelist/httplocalhost3000admingraphiql-413411.gql
src/authz/graphql-whitelist/httplocalhost4180manageractivity-25d785.gql
src/authz/graphql-whitelist/httplocalhost4180manageractivity-efc736.gql
src/nextapp/pages/manager/activity/index.tsx
src/services/keycloak/client-registration-service.ts

Fixes missing result field in activity summary

Add result to graphql

---

src/authz/graphql-whitelist/httplocalhost3000admingraphiql-413411.gql
src/authz/graphql-whitelist/httplocalhost4180manageractivity-25d785.gql
src/authz/graphql-whitelist/httplocalhost4180manageractivity-efc736.gql
src/nextapp/pages/manager/activity/index.tsx
src/services/keycloak/client-registration-service.ts

Co-authored-by: ikethecoder <ikethecoder@copeconsulting.ca>

Add result to graphql (#554)

---

src/lists/Application.js

hotfix-573-delete-app

---

src/nextapp/components/login-buttons/login-buttons.tsx

* add sync_org to feeder options
* change urls for ckan feeder
* initial working version of shared idp
* put back align in radio-card-group
* add the shared idp aud mapper
* add support for shared idp roles
* upd data rule for isShared
* upd controllers
* fix invalid idp shared check
* First pass at new login screens
* fix invalid query
* add namespace field to metrics
* upd types
* upd kong_http_requests_hourly_service grouping
* upd to handle Activity feed context
* Consolidate login pages to single entry
* Fix dialog, button fixes.
* minor cleanup
* make auto the default for issuer mode
* show error on failed deletion of issuer and svc acct
* add validation on issuer name
* add validation for availableScopes
* add in the delete access catch error
* Fix tabs losing data when …

Feature/shared idp cypress (#680)

---

src/authz/actions/filterByUserNSorSharedTrue.js
src/authz/enforcement.ts
src/authz/matrix.csv
src/batch/data-rules.js
src/batch/feed-worker.ts
src/lists/extensions/CredentialIssuerExt.ts
src/lists/extensions/UserExt.ts
src/nextapp/components/environment-plugins/templates/jwt-keycloak.ts
src/nextapp/components/environment-plugins/templates/kong-acl-only.ts
src/nextapp/components/environment-plugins/templates/kong-api-key-acl.ts
src/nextapp/components/namespace-manager/namespace-manager.tsx
src/nextapp/components/namespace-menu/namespace-menu.tsx
src/nextapp/shared/types/app.types.ts
src/nextapp/shared/types/query.types.ts
src/server.ts
src/services/keycloak/client-registration-service.ts
src/services/keycloak/templates/protocol-mappers/audience.ts
src/services/keystone/types.ts
src/services/keystone/user.ts
src/test/integrated/keystonejs/user.ts

* Fixes #718 
* Fixes #719
* Fixes #720
* Fixes #721
* Fixes #722
Feature branch: https://api-services-portal-feature-r126-hotfixes.apps.silver.devops.gov.bc.ca/

owner email fix inherit from name fix plugin template fix

---

src/mocks/handlers.js
src/mocks/resolvers/products.js
src/nextapp/components/authorization-profile-form/authentication-form.tsx
src/nextapp/components/authorization-profile-form/authorization-form.tsx
src/nextapp/components/authorization-profile-form/authorization-profile-dialog.tsx
src/nextapp/components/authorization-profile-form/client-management.tsx
src/nextapp/components/radio-card-group/radio-card-group.tsx
src/nextapp/components/radio-card-group/radio-card.tsx

Sprint 62 UI fixes

---

src/nextapp/pages/manager/namespaces/index.tsx

Fixes #736
**Preview URL** https://api-services-portal-feature-org-fixes.apps.silver.devops.gov.bc.ca/manager/namespaces

Fix org tooltip rendering logic

---

src/mocks/resolvers/consumers.js
src/nextapp/components/environment-config/credential-issuer-select.tsx
src/nextapp/components/environment-config/environment-config.tsx
src/nextapp/pages/manager/consumers/index.tsx

Fixes #665 and #671
- Load the consumers table first before access requests.
- Fix auth-code preventing environment edit.
**Preview URL** https://api-services-portal-feature-sprint-63-uifixes.apps.silver.devops.gov.bc.ca/
*See Products and Consumers pages

Sprint 63 UI Fixes

---

.github/workflows/ci-build-deploy.yaml

Stores `GWA_RES_SVR_CLIENT_SECRET` in Secret as flagged by ACS scanner.

Store GWA_RES_SVR_CLIENT_SECRET in Secret

---

src/nextapp/pages/docs/[slug].tsx
src/nextapp/pages/docs/index.tsx
src/nextapp/shared/data/links.ts

Fixes #737
**Preview URL:** https://api-services-portal-feature-remove-doc-tab.apps.silver.devops.gov.bc.ca/

Remove docs from the main nav

---

src/nextapp/components/new-namespace/new-namespace.tsx

Small UI tweaks that don't require a new branch for.
✔️ Adds language allowing dashes when creating a new namespace

Sprint 65 UI Fixes

---

.github/workflows/scripts/feeder-init/platform-authz-profile.yaml
feeds/ckan/index.js
feeds/kong/index.js
feeds/logger.js
feeds/prometheus/index.js
feeds/utils/portal.js
feeds/utils/results.js
feeds/utils/transfers.js
src/batch/feed-worker.ts
src/batch/transformations/toString.ts
src/batch/transformations/toStringDefaultArray.ts
src/nextapp/pages/profile.tsx
src/package-lock.json
src/package.json
src/services/report/ops-metrics.ts
src/yarn.lock

Preview: https://api-services-portal-feature-ops-metrics-fix.apps.silver.devops.gov.bc.ca

Feature Ops Metrics fix

---

src/logger.ts
src/services/uma2/resource-registration-service.ts
src/test/integrated/keycloak/client.ts

increase max records for query resources

---

e2e/cypress/fixtures/apiowner.json
e2e/cypress/fixtures/developer.json
e2e/cypress/fixtures/manage-control-config-setting.json
e2e/cypress/fixtures/manage-control/kong-plugin-config.json
e2e/cypress/fixtures/rate-limiting-902.yml
e2e/cypress/pageObjects/apiDirectory.ts
e2e/cypress/pageObjects/consumers.ts
e2e/cypress/pageObjects/products.ts
e2e/cypress/pageObjects/serviceAccounts.ts
e2e/cypress/support/auth-commands.ts
e2e/cypress/support/global.d.ts
e2e/cypress/tests/09-update-product-env/07-kong-public-auth.ts
e2e/cypress/tests/10-clear-resources/03-delete-service-acc.ts
e2e/cypress/tests/15-org-assignment/01-client-cred-team-access.ts

1)Cypress test to verify free (Public) access
2)Cypress Test - Delete Service account
3)Cypress Test - Verify rate_limiting_902 and rate_limiting plugins by applying them to different level 
4)Cypress Test for Org Admin

Added following scenarios:

---

src/authz/graphql-whitelist/httplocalhost4180managerconsumers-386f4b.gql
src/nextapp/components/access-request/grant-access-dialog.tsx

#632 
Quick fix preventing consumer access of inactive environments.

filter out inactive environments from drop down

---

src/nextapp/pages/manager/consumers/[id].tsx
src/nextapp/pages/manager/consumers/index.tsx
src/services/workflow/consumer-management.ts

Fixes #664 
Opting to display more descriptive error messages.

Enhanced error messaging for consumer and product deletion

---

src/services/workflow/consumer-management.ts

Fixed consumers appearing multiple times

---

src/nextapp/pages/devportal/api-directory/[id].tsx

---
🚀 Feature branch deployment: https://api-services-portal-feature-product-sorting.apps.silver.devops.gov.bc.ca

Sort products by name alphabetically

---

src/nextapp/components/edit-display-name/edit-display-name.tsx
src/services/keycloak/namespace-details.ts

display name min 3 chars

---

src/nextapp/pages/devportal/api-directory/[id].tsx
src/nextapp/pages/devportal/api-directory/your-products.tsx
src/nextapp/pages/manager/products/index.tsx

Ran full cypress test suite before and after changes and observed no differences.
Fixes #1076

Portal uses API v3 where appropriate

---

src/nextapp/components/no-gateway-redirect/no-gateway-redirect.tsx

super minor change, tested on feature branch
---
🚀 Feature branch deployment: https://api-services-portal-feature-gw-redirect.apps.silver.devops.gov.bc.ca

reduce timeout on redirect

---

feeds/testdata/dataset.json
src/batch/data-rules.js

Fixes #1198 
---
🚀 Feature branch deployment: https://api-services-portal-feature-fix-ckan-contacts.apps.silver.devops.gov.bc.ca

Fix syncing contacts and resources from CKAN
